# Generated by Codex on 2026-01-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alianzas", "0004_alter_alianza_correo_electronico"),
    ]

    operations = [
        migrations.AddField(
            model_name="alianza",
            name="correo_extra_1",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="alianza",
            name="correo_extra_2",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
