# Generated by Django 5.2.8 on 2025-11-19 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_alter_cliente_comision1_alter_cliente_comision10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('servicio', models.CharField(blank=True, max_length=50, null=True)),
                ('factura', models.CharField(max_length=100)),
                ('num_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('monto_dispersion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comision_porcentaje', models.DecimalField(decimal_places=4, editable=False, max_digits=7)),
                ('monto_comision', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('num_factura_honorarios', models.CharField(blank=True, max_length=100, null=True)),
                ('total_honorarios', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('estatus_proceso', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviada', 'Enviada'), ('Aplicada', 'Aplicada')], default='Pendiente', max_length=20)),
                ('comentarios', models.CharField(blank=True, max_length=255, null=True)),
                ('num_periodo', models.CharField(blank=True, max_length=50, null=True)),
                ('estatus_periodo', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cerrado', 'Cerrado'), ('Timbrado', 'Timbrado'), ('Enviado', 'Enviado'), ('Enviado ind.', 'Enviado ind.'), ('Drive', 'Drive')], default='Pendiente', max_length=20)),
                ('estatus_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
