# Generated by Django 5.2.8 on 2025-11-24 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispersiones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispersion',
            old_name='factura',
            new_name='facturadora',
        ),
    ]
