# Generated by Django 5.2.8 on 2025-12-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='medio',
            field=models.CharField(choices=[('Remarketing', 'Remarketing'), ('Alianzas', 'Alianzas'), ('Lead', 'Lead'), ('Procompite', 'Procompite'), ('Ejecutivos', 'Ejecutivos'), ('Personales', 'Personales'), ('Expos / Eventos Deportivos', 'Expos / Eventos Deportivos')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Todos', 'Todos'), ('Fiscal', 'Fiscal'), ('Auto-ahorro', 'Auto-ahorro'), ('CheckUp', 'CheckUp'), ('Hidrocarburos', 'Hidrocarburos'), ('Monederos', 'Monederos'), ('Mutualink', 'Mutualink'), ('PRAIDS', 'PRAIDS'), ('PROCOM', 'PROCOM'), ('TPV', 'TPV'), ('Valuación de activos intangibles', 'Valuación de activos intangibles'), ('Venta de empresas', 'Venta de empresas'), ('VP360', 'VP360'), ('Préstamos', 'Préstamos'), ('Reembolsos', 'Reembolsos')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio2',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Todos', 'Todos'), ('Fiscal', 'Fiscal'), ('Auto-ahorro', 'Auto-ahorro'), ('CheckUp', 'CheckUp'), ('Hidrocarburos', 'Hidrocarburos'), ('Monederos', 'Monederos'), ('Mutualink', 'Mutualink'), ('PRAIDS', 'PRAIDS'), ('PROCOM', 'PROCOM'), ('TPV', 'TPV'), ('Valuación de activos intangibles', 'Valuación de activos intangibles'), ('Venta de empresas', 'Venta de empresas'), ('VP360', 'VP360'), ('Préstamos', 'Préstamos'), ('Reembolsos', 'Reembolsos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio3',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Todos', 'Todos'), ('Fiscal', 'Fiscal'), ('Auto-ahorro', 'Auto-ahorro'), ('CheckUp', 'CheckUp'), ('Hidrocarburos', 'Hidrocarburos'), ('Monederos', 'Monederos'), ('Mutualink', 'Mutualink'), ('PRAIDS', 'PRAIDS'), ('PROCOM', 'PROCOM'), ('TPV', 'TPV'), ('Valuación de activos intangibles', 'Valuación de activos intangibles'), ('Venta de empresas', 'Venta de empresas'), ('VP360', 'VP360'), ('Préstamos', 'Préstamos'), ('Reembolsos', 'Reembolsos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='vendedor',
            field=models.CharField(choices=[('Bernardo', 'Bernardo'), ('Alfredo', 'Alfredo'), ('Gabriel', 'Gabriel')], max_length=50),
        ),
    ]
