# Generated by Django 5.2.8 on 2025-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_alter_cita_medio_alter_cita_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='lugar',
            field=models.CharField(blank=True, choices=[('Oficina de Enrok', 'Oficina de Enrok'), ('Oficina del cliente', 'Oficina del cliente'), ('Zoom', 'Zoom')], max_length=50, null=True),
        ),
    ]
