# Generated by Django 5.2.8 on 2025-12-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_alter_cita_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='posibilidad',
            field=models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=50, null=True),
        ),
    ]
