# Generated by Django 5.2.8 on 2025-12-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_cita_posibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estatus_seguimiento',
            field=models.CharField(blank=True, choices=[('Esperando respuesta del cliente', 'Esperando respuesta del cliente'), ('Agendar nueva cita', 'Agendar nueva cita'), ('Solicitud de propuesta', 'Solicitud de propuesta'), ('Elaboración de propuesta', 'Elaboración de propuesta'), ('Propuesta enviada', 'Propuesta enviada'), ('Se envió auditoría Laboral', 'Se envió auditoría Laboral'), ('Stand by', 'Stand by'), ('Pendiente de cierre', 'Pendiente de cierre'), ('En activación', 'En activación'), ('Reclutando', 'Reclutando'), ('Activo', 'Activo'), ('No está interesado en este servicio', 'No está interesado en este servicio'), ('Fuera de su presupuesto', 'Fuera de su presupuesto')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Todos', 'Todos'), ('Fiscal', 'Fiscal'), ('Auto-ahorro', 'Auto-ahorro'), ('CheckUp', 'CheckUp'), ('Efectivo', 'Efectivo'), ('Hidrocarburos', 'Hidrocarburos'), ('Monederos', 'Monederos'), ('Mutualink', 'Mutualink'), ('PRAIDS', 'PRAIDS'), ('PROCOM', 'PROCOM'), ('TPV', 'TPV'), ('Valuación de activos intangibles', 'Valuación de activos intangibles'), ('Venta de empresas', 'Venta de empresas'), ('VP360', 'VP360'), ('Préstamos', 'Préstamos'), ('Reembolsos', 'Reembolsos')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio2',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Todos', 'Todos'), ('Fiscal', 'Fiscal'), ('Auto-ahorro', 'Auto-ahorro'), ('CheckUp', 'CheckUp'), ('Efectivo', 'Efectivo'), ('Hidrocarburos', 'Hidrocarburos'), ('Monederos', 'Monederos'), ('Mutualink', 'Mutualink'), ('PRAIDS', 'PRAIDS'), ('PROCOM', 'PROCOM'), ('TPV', 'TPV'), ('Valuación de activos intangibles', 'Valuación de activos intangibles'), ('Venta de empresas', 'Venta de empresas'), ('VP360', 'VP360'), ('Préstamos', 'Préstamos'), ('Reembolsos', 'Reembolsos')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio3',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Todos', 'Todos'), ('Fiscal', 'Fiscal'), ('Auto-ahorro', 'Auto-ahorro'), ('CheckUp', 'CheckUp'), ('Efectivo', 'Efectivo'), ('Hidrocarburos', 'Hidrocarburos'), ('Monederos', 'Monederos'), ('Mutualink', 'Mutualink'), ('PRAIDS', 'PRAIDS'), ('PROCOM', 'PROCOM'), ('TPV', 'TPV'), ('Valuación de activos intangibles', 'Valuación de activos intangibles'), ('Venta de empresas', 'Venta de empresas'), ('VP360', 'VP360'), ('Préstamos', 'Préstamos'), ('Reembolsos', 'Reembolsos')], max_length=100, null=True),
        ),
    ]
