# Generated by Django 5.2.8 on 2026-04-27 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_alter_cita_estatus_seguimiento_alter_cita_servicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='vendedor_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Todos', 'Todos'), ('Fiscal', 'Fiscal'), ('Auto-ahorro', 'Auto-ahorro'), ('CheckUp', 'CheckUp'), ('Efectivo', 'Efectivo'), ('Hidrocarburos', 'Hidrocarburos'), ('Monederos', 'Monederos'), ('Mutualink', 'Mutualink'), ('PRAIDS', 'PRAIDS'), ('PROCOM', 'PROCOM'), ('TPV', 'TPV'), ('Valuación de activos intangibles', 'Valuación de activos intangibles'), ('Venta de empresas', 'Venta de empresas'), ('VP360', 'VP360'), ('Préstamos', 'Préstamos'), ('Reembolsos', 'Reembolsos'), ('Licitación', 'Licitación'), ('Creación de empresa', 'Creación de empresa'), ('DC-3', 'DC-3'), ('Venta de combustible', 'Venta de combustible')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio2',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Todos', 'Todos'), ('Fiscal', 'Fiscal'), ('Auto-ahorro', 'Auto-ahorro'), ('CheckUp', 'CheckUp'), ('Efectivo', 'Efectivo'), ('Hidrocarburos', 'Hidrocarburos'), ('Monederos', 'Monederos'), ('Mutualink', 'Mutualink'), ('PRAIDS', 'PRAIDS'), ('PROCOM', 'PROCOM'), ('TPV', 'TPV'), ('Valuación de activos intangibles', 'Valuación de activos intangibles'), ('Venta de empresas', 'Venta de empresas'), ('VP360', 'VP360'), ('Préstamos', 'Préstamos'), ('Reembolsos', 'Reembolsos'), ('Licitación', 'Licitación'), ('Creación de empresa', 'Creación de empresa'), ('DC-3', 'DC-3'), ('Venta de combustible', 'Venta de combustible')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio3',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Todos', 'Todos'), ('Fiscal', 'Fiscal'), ('Auto-ahorro', 'Auto-ahorro'), ('CheckUp', 'CheckUp'), ('Efectivo', 'Efectivo'), ('Hidrocarburos', 'Hidrocarburos'), ('Monederos', 'Monederos'), ('Mutualink', 'Mutualink'), ('PRAIDS', 'PRAIDS'), ('PROCOM', 'PROCOM'), ('TPV', 'TPV'), ('Valuación de activos intangibles', 'Valuación de activos intangibles'), ('Venta de empresas', 'Venta de empresas'), ('VP360', 'VP360'), ('Préstamos', 'Préstamos'), ('Reembolsos', 'Reembolsos'), ('Licitación', 'Licitación'), ('Creación de empresa', 'Creación de empresa'), ('DC-3', 'DC-3'), ('Venta de combustible', 'Venta de combustible')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='vendedor',
            field=models.CharField(choices=[('Bernardo', 'Bernardo'), ('Alfredo', 'Alfredo'), ('Gabriel', 'Gabriel'), ('Noah', 'Noah'), ('Luis Q.', 'Luis Q.')], max_length=50),
        ),
    ]
