# Generated by Django 5.2.8 on 2026-04-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_cita_vendedor_usuario_alter_cita_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='vendedor',
            field=models.CharField(blank=True, choices=[('Bernardo', 'Bernardo'), ('Alfredo', 'Alfredo'), ('Gabriel', 'Gabriel'), ('Noah', 'Noah'), ('Luis Q.', 'Luis Q.')], max_length=50, null=True),
        ),
    ]
