# Generated by Django 5.2.8 on 2025-11-19 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alianzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('servicio', models.CharField(choices=[('PROCOM', 'PROCOM'), ('MUTUALINK', 'Mutualink'), ('PRESTAMO', 'Préstamo'), ('PRAIDS', 'PRAIDS'), ('MONEDEROS', 'Monederos'), ('HIDROCARBUROS', 'Hidrocarburos')], max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('comision1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comision2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comision3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comision4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comision5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comision6', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comision7', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comision8', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comision9', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comision10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comisionista1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_comisionista1', to='alianzas.alianza')),
                ('comisionista10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_comisionista10', to='alianzas.alianza')),
                ('comisionista2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_comisionista2', to='alianzas.alianza')),
                ('comisionista3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_comisionista3', to='alianzas.alianza')),
                ('comisionista4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_comisionista4', to='alianzas.alianza')),
                ('comisionista5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_comisionista5', to='alianzas.alianza')),
                ('comisionista6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_comisionista6', to='alianzas.alianza')),
                ('comisionista7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_comisionista7', to='alianzas.alianza')),
                ('comisionista8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_comisionista8', to='alianzas.alianza')),
                ('comisionista9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_comisionista9', to='alianzas.alianza')),
            ],
        ),
    ]
