# Generated by Django 5.2.8 on 2026-04-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='servicio',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Todos', 'Todos'), ('Auto-ahorro', 'Auto-ahorro'), ('CheckUp', 'CheckUp'), ('Contabilidad', 'Contabilidad'), ('Efectivo', 'Efectivo'), ('Fiscal', 'Fiscal'), ('Hidrocarburos', 'Hidrocarburos'), ('Laboral', 'Laboral'), ('Monederos', 'Monederos'), ('Mutualink', 'Mutualink'), ('PRAIDS', 'PRAIDS'), ('PROCOM', 'PROCOM'), ('TPV', 'TPV'), ('Valuación de activos intangibles', 'Valuación de activos intangibles'), ('Venta de empresas', 'Venta de empresas'), ('VP360', 'VP360'), ('Préstamos', 'Préstamos'), ('Reembolsos', 'Reembolsos'), ('Licitación', 'Licitación'), ('Creación de empresa', 'Creación de empresa'), ('DC-3', 'DC-3'), ('Venta de combustible', 'Venta de combustible')], max_length=100),
        ),
    ]
