# Generated by Django 5.2.8 on 2025-11-19 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alianzas', '0001_initial'),
        ('clientes', '0003_alter_cliente_comision1_alter_cliente_comision10_and_more'),
        ('dispersiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=50)),
                ('porcentaje', models.DecimalField(decimal_places=6, max_digits=9)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periodo_mes', models.IntegerField()),
                ('periodo_anio', models.IntegerField()),
                ('liberable_desde', models.DateField()),
                ('liberada', models.BooleanField(default=False)),
                ('estatus_pago_dispersion', models.CharField(max_length=50)),
                ('fecha_dispersion', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('comisionista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alianzas.alianza')),
                ('dispersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='dispersiones.dispersion')),
            ],
        ),
    ]
