# Generated by Django 5.2.8 on 2025-11-19 21:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alianzas', '0001_initial'),
        ('comisiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_mes', models.IntegerField()),
                ('periodo_anio', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('comisionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_comision', to='alianzas.alianza')),
            ],
        ),
    ]
